# Sample file
sample_file: "samples.csv"

# Source data
sourcedir: "~/Pycharmprojects/snakemake-call-methylation/data"

# results are stored here
results: "results"

# Directory containing fast5 files
f5: "/home/bayraktar/PycharmProjects/snakemake-call-methylation/data/fast5"

# Directory containing fastq files
fq: "/home/bayraktar/PycharmProjects/snakemake-call-methylation/data/fastq"

# Genome reference
ref: "/home/bayraktar/PycharmProjects/snakemake-call-methylation/data/Homo_sapiens.GRCh38.dna.primary_assembly.fa"
